<?php

use Illuminate\Database\Seeder;

class AccountDetailTypeSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
    	DB::table('account_detail_type')->truncate();


  //       DB::table('account_detail_type')->insert( [ 'account_category_type_id' => 1, 'name' => 'Account Receivable (A/R)', 									'description' => 'Accounts receivable (also called A/R, Debtors, or Trade and other receivables) tracks money that customers owe you for products or services, and payments customers make. QuickBooks Online Plus automatically creates one Accounts receivable account for you. Most businesses need only one. Each customer has a register, which functions like an Accounts receivable account for each customer.' ] );

  //       DB::table('account_detail_type')->insert( [ 'account_category_type_id' => 2, 'name' => 'Allowance for bad debts', 									'description' => 'Use Allowance for bad debts to estimate the part of Accounts Receivable that you think you might not collect. Use this only if you are keeping your books on the accrual basis.' ] );
  //       DB::table('account_detail_type')->insert( [ 'account_category_type_id' => 2, 'name' => 'Assets available for sale', 								'description' => 'Use Assets available for sale to track assets that are available for sale that are not expected to be held for a long period of time.' ] );
  //       DB::table('account_detail_type')->insert( [ 'account_category_type_id' => 2, 'name' => 'Development Costs', 										'description' => 'Use Development costs to track amounts you deposit or set aside to arrange for financing, such as an SBA loan, or for deposits in anticipation of the purchase of property or other assets. When the deposit is refunded, or the purchase takes place, remove the amount from this account.' ] );
  //       DB::table('account_detail_type')->insert( [ 'account_category_type_id' => 2, 'name' => 'Employee Cash Advances', 									'description' => 'Use Employee cash advances to track employee wages and salary you issue to an employee early, or other non-salary money given to employees. If you make a loan to an employee, use the Current asset account type called Loans to others, instead.' ] );
  //       DB::table('account_detail_type')->insert( [ 'account_category_type_id' => 2, 'name' => 'Inventory', 												'description' => 'Use Inventory to track the cost of goods your business purchases for resale. When the goods are sold, assign the sale to a Cost of sales account.' ] );
  //       DB::table('account_detail_type')->insert( [ 'account_category_type_id' => 2, 'name' => 'Investments - Other', 										'description' => 'Use Investments - Other to track the value of investments not covered by other investment account types. Examples include publicly-traded shares, coins, or gold.' ] );
  //       DB::table('account_detail_type')->insert( [ 'account_category_type_id' => 2, 'name' => 'Loans To Officers', 										'description' => 'If you operate your business as a Corporation, use Loans to officers to track money loaned to officers of your business.' ] );
  //       DB::table('account_detail_type')->insert( [ 'account_category_type_id' => 2, 'name' => 'Loans To Others', 											'description' => 'Use Loans to others to track money your business loans to other people or businesses. This type of account is also referred to as Notes Receivable. For early salary payments to employees, use Employee cash advances, instead.' ] );
  //       DB::table('account_detail_type')->insert( [ 'account_category_type_id' => 2, 'name' => 'Loans To Shareholders', 									'description' => 'If you operate your business as a Corporation, use Loans to Shareholders to track money your business loans to its shareholders.' ] );
  //       DB::table('account_detail_type')->insert( [ 'account_category_type_id' => 2, 'name' => 'Other current assets', 										'description' => 'Use Other current assets for current assets not covered by the other types. Current assets are likely to be converted to cash or used up in a year.' ] );
  //       DB::table('account_detail_type')->insert( [ 'account_category_type_id' => 2, 'name' => 'Prepaid Expenses', 											'description' => 'Use Prepaid expenses to track payments for expenses that you will not recognise until your next accounting period. When you recognise the expense, make a journal entry to transfer money from this account to the expense account.' ] );
  //       DB::table('account_detail_type')->insert( [ 'account_category_type_id' => 2, 'name' => 'Retainage', 												'description' => 'Use Retainage if your customers regularly hold back a portion of a contract amount until you have completed a project. This type of account is often used in the construction industry, and only if you record income on an accrual basis.' ] );
  //       DB::table('account_detail_type')->insert( [ 'account_category_type_id' => 2, 'name' => 'Undeposited Funds', 										'description' => 'Use Undeposited funds for cash or cheques from sales that have not been deposited yet. For petty cash, use Cash on hand, instead.' ] );

  //       DB::table('account_detail_type')->insert( [ 'account_category_type_id' => 3, 'name' => 'Bank', 														'description' => 'Use Bank accounts to track all your current activity, including debit card transactions. Each current account your company has at a bank or other financial institution should have its own Bank type account in QuickBooks Online Plus.' ] );
  //       DB::table('account_detail_type')->insert( [ 'account_category_type_id' => 3, 'name' => 'Cash and cash equivalents', 								'description' => 'Use Cash and Cash Equivalents to track cash or assets that can be converted into cash immediately. For example, marketable securities and Treasury bills.' ] );
  //       DB::table('account_detail_type')->insert( [ 'account_category_type_id' => 3, 'name' => 'Cash on hand', 												'description' => 'Use a Cash on hand account to track cash your company keeps for occasional expenses, also called petty cash. To track cash from sales that have not been deposited yet, use a pre-created account called Undeposited funds, instead.' ] );
  //       DB::table('account_detail_type')->insert( [ 'account_category_type_id' => 3, 'name' => 'Client trust account', 										'description' => 'Use Client trust accounts for money held by you for the benefit of someone else. For example, trust accounts are often used by attorneys to keep track of expense money their customers have given them. Often, to keep the amount in a trust account from looking like it is yours, the amount is offset in a "contra" liability account (a Current Liability).' ] );
  //       DB::table('account_detail_type')->insert( [ 'account_category_type_id' => 3, 'name' => 'Money market', 												'description' => 'Use Money market to track amounts in money market accounts. For investments, see Current Assets, instead.' ] );
  //       DB::table('account_detail_type')->insert( [ 'account_category_type_id' => 3, 'name' => 'Retns Held in Trust', 										'description' => 'Use Rents held in trust to track deposits and rent held on behalf of the property owners. Typically only property managers use this type of account.' ] );
  //       DB::table('account_detail_type')->insert( [ 'account_category_type_id' => 3, 'name' => 'Savings', 													'description' => 'Use Savings accounts to track your savings and CD activity. Each savings account your company has at a bank or other financial institution should have its own Savings type account. For investments, see Current Assets, instead.' ] );

		// DB::table('account_detail_type')->insert( [ 'account_category_type_id' => 4, 'name' => 'Accumulated depletion', 									'description' => 'Use Accumulated depletion to track how much you deplete a natural resource.' ] );
		// DB::table('account_detail_type')->insert( [ 'account_category_type_id' => 4, 'name' => 'Accumulated depreciation on property, plant and equipment', 'description' => 'Use Accumulated depreciation on property, plant and equipment to track how much you depreciate a fixed asset (a physical asset you do not expect to convert to cash during one year of normal operations).' ] );
		// DB::table('account_detail_type')->insert( [ 'account_category_type_id' => 4, 'name' => 'Buildings', 												'description' => 'Use Buildings to track the cost of structures you own and use for your business. If you have a business in your home, consult your accountant. Use a Land account for the land portion of any real property you own, splitting the cost of the property between land and building in a logical method. A common method is to mimic the land-to-building ratio on the property tax statement.' ] );
		// DB::table('account_detail_type')->insert( [ 'account_category_type_id' => 4, 'name' => 'Depletable Assets', 										'description' => 'Use Depletable assets to track natural resources, such as timberlands, oil wells, and mineral deposits.' ] );
		// DB::table('account_detail_type')->insert( [ 'account_category_type_id' => 4, 'name' => 'Furniture and Fixtures', 									'description' => 'Use Furniture and fixtures to track any furniture and fixtures your business owns and uses, like a dental chair or sales booth.' ] );
		// DB::table('account_detail_type')->insert( [ 'account_category_type_id' => 4, 'name' => 'Land', 														'description' => 'Use Land to track assets that are not easily convertible to cash or not expected to become cash within the next year. For example, leasehold improvements.' ] );
		// DB::table('account_detail_type')->insert( [ 'account_category_type_id' => 4, 'name' => 'Leasehold Improvements', 									'description' => 'Use Leasehold improvements to track improvements to a leased asset that increases the asset’s value. For example, if you carpet a leased office space and are not reimbursed, that is a leasehold improvement.' ] );
		// DB::table('account_detail_type')->insert( [ 'account_category_type_id' => 4, 'name' => 'Machinery and equipment', 									'description' => 'Use Machinery and equipment to track computer hardware, as well as any other non-furniture fixtures or devices owned and used for your business. This includes equipment that you ride, like tractors and lawn mowers. Cars and lorries, however, should be tracked with Vehicle accounts, instead.' ] );
		// DB::table('account_detail_type')->insert( [ 'account_category_type_id' => 4, 'name' => 'Other fixed assets', 										'description' => 'Use Other fixed asset for fixed assets that are not covered by other asset types. Fixed assets are physical property that you use in your business and that you do not expect to convert to cash or be used up during one year of normal operations.' ] );
		// DB::table('account_detail_type')->insert( [ 'account_category_type_id' => 4, 'name' => 'Vehicles', 													'description' => 'Use Vehicles to track the value of vehicles your business owns and uses for business. This includes off-road vehicles, air planes, helicopters, and boats. If you use a vehicle for both business and personal use, consult your accountant to see how you should track its value.' ] );

		// DB::table('account_detail_type')->insert( [ 'account_category_type_id' => 5, 'name' => 'Accumulated amortisation of non-current assets', 			'description' => 'Use Accumulated amortisation of non-current assets to track how much you have amortised an asset whose type is Non-Current Asset.' ] );
		// DB::table('account_detail_type')->insert( [ 'account_category_type_id' => 5, 'name' => 'Assets held for sale', 										'description' => 'Use Assets held for sale to track assets of a company that are available for sale that are not expected to be held for a long period of time.' ] );
		// DB::table('account_detail_type')->insert( [ 'account_category_type_id' => 5, 'name' => 'Deferred tax', 												'description' => 'Use Deferred tax for tax liabilities or assets that are to be used in future accounting periods.' ] );
		// DB::table('account_detail_type')->insert( [ 'account_category_type_id' => 5, 'name' => 'Goodwill', 													'description' => 'Use Goodwill only if you have acquired another company. It represents the intangible assets of the acquired company which gave it an advantage, such as favourable government relations, business name, outstanding credit ratings, location, superior management, customer lists, product quality, or good labour relations.' ] );
		// DB::table('account_detail_type')->insert( [ 'account_category_type_id' => 5, 'name' => 'Intangible Assets', 										'description' => 'Use Intangible assets to track intangible assets that you plan to amortise. Examples include franchises, customer lists, copyrights, and patents.' ] );
		// DB::table('account_detail_type')->insert( [ 'account_category_type_id' => 5, 'name' => 'Lease Buyout', 												'description' => 'Use Lease buyout to track lease payments to be applied toward the purchase of a leased asset. You do not track the leased asset itself until you purchase it.' ] );
		// DB::table('account_detail_type')->insert( [ 'account_category_type_id' => 5, 'name' => 'Licenses', 													'description' => 'Use Licences to track non-professional licences for permission to engage in an activity, like selling alcohol or radio broadcasting. For fees associated with professional licences granted to individuals, use a Legal and professional fees expense account, instead.' ] );
		// DB::table('account_detail_type')->insert( [ 'account_category_type_id' => 5, 'name' => 'Long-term investments', 									'description' => 'Use Long-term investments to track investments that have a maturity date of longer than one year.' ] );
		// DB::table('account_detail_type')->insert( [ 'account_category_type_id' => 5, 'name' => 'Organisational Costs', 										'description' => 'Use Organisational costs to track costs incurred when forming a partnership or corporation. The costs include the legal and accounting costs necessary to organise the company, facilitate the filings of the legal documents, and other paperwork.' ] );
		// DB::table('account_detail_type')->insert( [ 'account_category_type_id' => 5, 'name' => 'Other non-current assets', 									'description' => 'Use Other non-current assets to track assets not covered by other types. Non-current assets are long-term assets that are expected to provide value for more than one year.' ] );
		// DB::table('account_detail_type')->insert( [ 'account_category_type_id' => 5, 'name' => 'Security Deposits', 										'description' => 'Use Security deposits to track funds you have paid to cover any potential costs incurred by damage, loss, or theft. The funds should be returned to you at the end of the contract. If you collect deposits, use an Other current liabilities account (a Current liability account).' ] );

		// DB::table('account_detail_type')->insert( [ 'account_category_type_id' => 6, 'name' => 'Accounts Payable (A/P)', 									'description' => 'Accounts payable (also called A/P, Trade and other payables, or Creditors) tracks amounts you owe to your suppliers. QuickBooks Online Plus automatically creates one Accounts Payable account for you. Most businesses need only one.' ] );

		// DB::table('account_detail_type')->insert( [ 'account_category_type_id' => 7, 'name' => 'Credit card', 												'description' => 'Credit card accounts track the balance due on your business credit cards. Create one Credit card account for each credit card account your business uses.' ] );

		// DB::table('account_detail_type')->insert( [ 'account_category_type_id' => 8, 'name' => 'Accrued liabilities', 										'description' => 'Use Accrued Liabilities to track expenses that a business has incurred but has not yet paid. For example, pensions for companies that contribute to a pension fund for their employees for their retirement.' ] );
		// DB::table('account_detail_type')->insert( [ 'account_category_type_id' => 8, 'name' => 'Client Trust Accounts - Liabilities', 						'description' => 'Use Client Trust accounts - liabilities to offset Client Trust accounts in assets. Amounts in these accounts are held by your business on behalf of others. They do not belong to your business, so should not appear to be yours on your balance sheet. This "contra" account takes care of that, as long as the two balances match.' ] );
		// DB::table('account_detail_type')->insert( [ 'account_category_type_id' => 8, 'name' => 'Current Tax Liability', 									'description' => 'Use Current tax liability to track the total amount of taxes collected but not yet paid to the government.' ] );
		// DB::table('account_detail_type')->insert( [ 'account_category_type_id' => 8, 'name' => 'Current Portion of obligations under finance leases', 		'description' => 'Use Current portion of obligations under finance leases to track the value of lease payments due within the next 12 months.' ] );
		// DB::table('account_detail_type')->insert( [ 'account_category_type_id' => 8, 'name' => 'Dividends payable', 										'description' => 'Use Dividends payable to track dividends that are owed to shareholders but have not yet been paid.' ] );
		// DB::table('account_detail_type')->insert( [ 'account_category_type_id' => 8, 'name' => 'Income tax payable', 										'description' => 'Use Income tax payable to track monies that are due to pay the company’s income tax liabilties.' ] );
		// DB::table('account_detail_type')->insert( [ 'account_category_type_id' => 8, 'name' => 'Insurance payable', 										'description' => 'Use Insurance payable to keep track of insurance amounts due. This account is most useful for businesses with monthly recurring insurance expenses.' ] );
		// DB::table('account_detail_type')->insert( [ 'account_category_type_id' => 8, 'name' => 'Line of Credit', 											'description' => 'Use Line of credit to track the balance due on any lines of credit your business has. Each line of credit your business has should have its own Line of credit account.' ] );
		// DB::table('account_detail_type')->insert( [ 'account_category_type_id' => 8, 'name' => 'Loan Payable', 												'description' => 'Use Loan payable to track loans your business owes which are payable within the next twelve months. For longer-term loans, use the Long-term liability called Notes payable, instead.' ] );
		// DB::table('account_detail_type')->insert( [ 'account_category_type_id' => 8, 'name' => 'Other current liabilities', 								'description' => 'Use Other current liabilities to track monies owed by the company and due within one year.' ] );
		// DB::table('account_detail_type')->insert( [ 'account_category_type_id' => 8, 'name' => 'Payroll clearing', 											'description' => 'Use Payroll clearing to keep track of any non-tax amounts that you have deducted from employee paycheques or that you owe as a result of doing payroll. When you forward money to the appropriate suppliers, deduct the amount from the balance of this account. Do not use this account for tax amounts you have withheld or owe from paying employee wages. For those amounts, use the Payroll liabilities payable account instead.' ] );
		// DB::table('account_detail_type')->insert( [ 'account_category_type_id' => 8, 'name' => 'Payroll liabilities', 										'description' => 'Use Payroll liabilities to keep track of tax amounts that you owe to government agencies as a result of paying wages. This includes taxes withheld, health care premiums, employment insurance, government pensions, etc. When you forward the money to the government agency, deduct the amount from the balance of this account.' ] );
		// DB::table('account_detail_type')->insert( [ 'account_category_type_id' => 8, 'name' => 'Prepaid Expenses Payable', 									'description' => 'Use Prepaid expenses payable to track items such as property taxes that are due, but not yet deductible as an expense because the period they cover has not yet passed.' ] );
		// DB::table('account_detail_type')->insert( [ 'account_category_type_id' => 8, 'name' => 'Rents in trust - Liability', 								'description' => 'Use Rents in trust - liability to offset the Rents in trust amount in assets. Amounts in these accounts are held by your business on behalf of others. They do not belong to your business, so should not appear to be yours on your balance sheet. This "contra" account takes care of that, as long as the two balances match.' ] );
		// DB::table('account_detail_type')->insert( [ 'account_category_type_id' => 8, 'name' => 'Sales and service tax payable', 							'description' => 'Use Sales and service tax payable to track tax you have collected, but not yet remitted to your government tax agency. This includes value-added tax, goods and services tax, sales tax, and other consumption tax.' ] );

		// DB::table('account_detail_type')->insert( [ 'account_category_type_id' => 9, 'name' => 'Accrued holiday payable', 									'description' => 'Use Accrued holiday payable to track holiday earned but that has not been paid out to employees.' ] );
		// DB::table('account_detail_type')->insert( [ 'account_category_type_id' => 9, 'name' => 'Accrued non-current liabilities', 							'description' => 'Use Accrued Non-current liabilities to track expenses that a business has incurred but has not yet paid. For example, pensions for companies that contribute to a pension fund for their employees for their retirement.' ] );
		// DB::table('account_detail_type')->insert( [ 'account_category_type_id' => 9, 'name' => 'Liabilities related to assets held for sale', 				'description' => 'Use Liabilities related to assets held for sale to track any liabilities that are directly related to assets being sold or written off.' ] );
		// DB::table('account_detail_type')->insert( [ 'account_category_type_id' => 9, 'name' => 'Long-term debt', 											'description' => 'Use Long-term debt to track loans and obligations with a maturity of longer than one year. For example, mortgages.' ] );
		// DB::table('account_detail_type')->insert( [ 'account_category_type_id' => 9, 'name' => 'Notes Payable', 											'description' => 'Use Notes payable to track the amounts your business owes in long-term (over twelve months) loans. For shorter loans, use the Current liability account type called Loan payable, instead.' ] );
		// DB::table('account_detail_type')->insert( [ 'account_category_type_id' => 9, 'name' => 'Other non-current liabilities', 							'description' => 'Use Other non-current liabilities to track liabilities due in more than twelve months that do not fit the other Non-Current liability account types.' ] );
		// DB::table('account_detail_type')->insert( [ 'account_category_type_id' => 9, 'name' => 'Shareholder Notes Payable', 								'description' => 'Use Shareholder notes payable to track long-term loan balances your business owes its shareholders.' ] );

		// DB::table('account_detail_type')->insert( [ 'account_category_type_id' => 10, 'name' => 'Accumulated adjustment', 									'description' => 'Some corporations use this account to track adjustments to owner’s equity that are not attributable to net income.' ] );
		// DB::table('account_detail_type')->insert( [ 'account_category_type_id' => 10, 'name' => 'Dividend disbursed', 										'description' => 'Use Dividend disbursed to track a payment given to its shareholders out of the company’s retained earnings.' ] );
		// DB::table('account_detail_type')->insert( [ 'account_category_type_id' => 10, 'name' => 'Equity in earnings of subsidiaries', 						'description' => 'Use Equity in earnings of subsidiaries to track the original investment in shares of subsidiaries plus the share of earnings or losses from the operations of the subsidiary.' ] );
		// DB::table('account_detail_type')->insert( [ 'account_category_type_id' => 10, 'name' => 'Opening Balance Equity', 									'description' => 'QuickBooks Online Plus creates this account the first time you enter an opening balance for a balance sheet account. As you enter opening balances, QuickBooks Online Plus records the amounts in Opening balance equity. This ensures that you have a correct balance sheet for your company, even before you have finished entering all your company’s assets and liabilities.' ] );
		// DB::table('account_detail_type')->insert( [ 'account_category_type_id' => 10, 'name' => 'Ordinary shares', 											'description' => 'Corporations use Ordinary shares to track its ordinary shares in the hands of shareholders. The amount in this account should be the stated (or par) value of the stock.' ] );
		// DB::table('account_detail_type')->insert( [ 'account_category_type_id' => 10, 'name' => 'Other comprehensive income', 								'description' => 'Use Other comprehensive income to track the increases or decreases in income from various businesses that is not yet absorbed by the company.' ] );
		// DB::table('account_detail_type')->insert( [ 'account_category_type_id' => 10, 'name' => 'Owner\'s Equity', 											'description' => 'Corporations use Owner’s equity to show the cumulative net income or loss of their business as of the beginning of the financial year.' ] );
		// DB::table('account_detail_type')->insert( [ 'account_category_type_id' => 10, 'name' => 'Paid-in capital or surplus', 								'description' => 'Corporations use Paid-in capital to track amounts received from shareholders in exchange for shares that are over and above the shares’ stated (or par) value.' ] );
		// DB::table('account_detail_type')->insert( [ 'account_category_type_id' => 10, 'name' => 'Partner contributions', 									'description' => 'Partnerships use Partner contributions to track amounts partners contribute to the partnership during the year.' ] );
		// DB::table('account_detail_type')->insert( [ 'account_category_type_id' => 10, 'name' => 'Partner\'s Equity', 										'description' => 'Partnerships use Partner’s equity to show the income remaining in the partnership for each partner as of the end of the prior year.' ] );
		// DB::table('account_detail_type')->insert( [ 'account_category_type_id' => 10, 'name' => 'Preferred shares', 										'description' => 'Corporations use this account to track its preferred shares in the hands of shareholders. The amount in this account should be the stated (or par) value of the shares.' ] );
		// DB::table('account_detail_type')->insert( [ 'account_category_type_id' => 10, 'name' => 'Retained Earnings', 										'description' => 'QuickBooks Online Plus adds this account when you create your company. Retained earnings tracks net income from previous financial years. QuickBooks Online Plus automatically transfers your profit (or loss) to Retained earnings at the end of each financial year.' ] );
		// DB::table('account_detail_type')->insert( [ 'account_category_type_id' => 10, 'name' => 'Share Capital', 											'description' => 'Use Share capital to track the funds raised by issuing shares.' ] );
		// DB::table('account_detail_type')->insert( [ 'account_category_type_id' => 10, 'name' => 'Treasury shares', 											'description' => 'Corporations use Treasury shares to track amounts paid by the corporation to buy its own shares back from shareholders.' ] );

		// DB::table('account_detail_type')->insert( [ 'account_category_type_id' => 11, 'name' => 'Discounts/Refunds Given', 									'description' => 'Use Discounts/refunds given to track discounts you give to customers. This account typically has a negative balance so it offsets other income. For discounts from suppliers, use an expense account, instead.' ] );
		// DB::table('account_detail_type')->insert( [ 'account_category_type_id' => 11, 'name' => 'Non-Profit Income', 										'description' => 'Use Non-profit income to track money coming in if you are a non-profit organisation.' ] );
		// DB::table('account_detail_type')->insert( [ 'account_category_type_id' => 11, 'name' => 'Other Primary Income', 									'description' => 'Use Other primary income to track income from normal business operations that does not fall into another Income type.' ] );
		// DB::table('account_detail_type')->insert( [ 'account_category_type_id' => 11, 'name' => 'Revenue - General', 										'description' => 'Use Revenue - General to track income from normal business operations that do not fit under any other category.' ] );
		// DB::table('account_detail_type')->insert( [ 'account_category_type_id' => 11, 'name' => 'Sales - ratail', 											'description' => 'Use Sales - retail to track sales of goods/services that have a mark-up cost to consumers.' ] );
		// DB::table('account_detail_type')->insert( [ 'account_category_type_id' => 11, 'name' => 'Sales - whole sale', 										'description' => 'Use Sales - wholesale to track the sale of goods in quantity for resale purposes.' ] );
		// DB::table('account_detail_type')->insert( [ 'account_category_type_id' => 11, 'name' => 'Sales of Product Income', 									'description' => 'Use Sales of product income to track income from selling products. This can include all kinds of products, like crops and livestock, rental fees, performances, and food served.' ] );
  //       DB::table('account_detail_type')->insert( [ 'account_category_type_id' => 11, 'name' => 'Sales of Service Income',                                  'description' => 'Use Sales of product income to track income from selling products. This can include all kinds of products, like crops and livestock, rental fees, performances, and food served.' ] );
		// DB::table('account_detail_type')->insert( [ 'account_category_type_id' => 11, 'name' => 'Service/Fee Income', 										'description' => 'Use Service/fee income to track income from services you perform or ordinary usage fees you charge. For fees customers pay you for late payments or other uncommon situations, use an Other Income account type called Other miscellaneous income, instead.' ] );
		// DB::table('account_detail_type')->insert( [ 'account_category_type_id' => 11, 'name' => 'Unapplied Cash Payment Income', 							'description' => 'Unapplied Cash Payment Income reports the Cash Basis income from customers payments you have received but not applied to invoices or charges. In general, you would never use this directly on a purchase or sale transaction.' ] );

		// DB::table('account_detail_type')->insert( [ 'account_category_type_id' => 12, 'name' => 'Dividend income', 											'description' => 'Use Dividend income to track taxable dividends from investments.' ] );
		// DB::table('account_detail_type')->insert( [ 'account_category_type_id' => 12, 'name' => 'Interest earned', 											'description' => 'Use Interest earned to track interest from bank or savings accounts, investments, or interest payments to you on loans your business made.' ] );
		// DB::table('account_detail_type')->insert( [ 'account_category_type_id' => 12, 'name' => 'Loss on disposal of assets', 								'description' => 'Use Loss on disposal of assets to track losses realised on the disposal of assets.' ] );
		// DB::table('account_detail_type')->insert( [ 'account_category_type_id' => 12, 'name' => 'Other Investment Income', 									'description' => 'Use Other investment income to track other types of investment income that is not from dividends or interest.' ] );
		// DB::table('account_detail_type')->insert( [ 'account_category_type_id' => 12, 'name' => 'Other Miscellaneous Income', 								'description' => 'Use Other miscellaneous income to track income that is not from normal business operations, and does not fall into another Other Income type.' ] );
		// DB::table('account_detail_type')->insert( [ 'account_category_type_id' => 12, 'name' => 'Other operating income', 									'description' => 'Use Other operating income to track income from activities other than normal business operations. For example, Investment interest, foreign exchange gains, and rent income.' ] );
		// DB::table('account_detail_type')->insert( [ 'account_category_type_id' => 12, 'name' => 'Tax-Exempt Interest',	 									'description' => 'Use Tax-exempt interest to record interest that is not taxable, such as interest on money in tax-exempt retirement accounts, or interest from tax-exempt bonds.' ] );
		// DB::table('account_detail_type')->insert( [ 'account_category_type_id' => 12, 'name' => 'Unrealised loss on securities, net of tax', 				'description' => 'Use Unrealised loss on securities, net of tax to track losses on securities that have occurred but are yet been realised through a transaction. For example, shares whose value has fallen but that are still being held.' ] );

		// DB::table('account_detail_type')->insert( [ 'account_category_type_id' => 13, 'name' => 'Cost of labour - COS', 									'description' => 'Use Cost of labour - COS to track the cost of paying employees to produce products or supply services. It includes all employment costs, including food and transportation, if applicable.' ] );
		// DB::table('account_detail_type')->insert( [ 'account_category_type_id' => 13, 'name' => 'Equipment rental - COS', 									'description' => 'Use Equipment rental - COS to track the cost of renting equipment to produce products or services. If you purchase equipment, use a Fixed Asset account type called Machinery and equipment.' ] );
		// DB::table('account_detail_type')->insert( [ 'account_category_type_id' => 13, 'name' => 'Freight and delivery - COS', 								'description' => 'Use Freight and delivery - COS to track the cost of shipping/delivery of obtaining raw materials and producing finished goods for resale.' ] );
		// DB::table('account_detail_type')->insert( [ 'account_category_type_id' => 13, 'name' => 'Other costs of sales - COS', 								'description' => 'Use Other costs of sales - COS to track costs related to services or sales that you provide that do not fall into another Cost of Sales type.' ] );
		// DB::table('account_detail_type')->insert( [ 'account_category_type_id' => 13, 'name' => 'Supplies and materials - COS', 							'description' => 'Use Supplies and materials - COS to track the cost of raw goods and parts used or consumed when producing a product or providing a service.' ] );

		// DB::table('account_detail_type')->insert( [ 'account_category_type_id' => 14, 'name' => 'Advertising/Promotional', 									'description' => 'Use Advertising/promotional to track money spent promoting your company. You may want different accounts of this type to track different promotional efforts (Yellow Pages, newspaper, radio, flyers, events, and so on). If the promotion effort is a meal, use Promotional meals instead.' ] );
		// DB::table('account_detail_type')->insert( [ 'account_category_type_id' => 14, 'name' => 'Amortisation expense', 									'description' => 'Use Amortisation expense to track writing off of assets (such as intangible assets or investments) over the projected life of the assets.' ] );
		// DB::table('account_detail_type')->insert( [ 'account_category_type_id' => 14, 'name' => 'Auto', 													'description' => 'Use Auto to track costs associated with vehicles. You may want different accounts of this type to track petrol, repairs, and maintenance. If your business owns a car or lorry, you may want to track its value as a Fixed Asset, in addition to tracking its expenses.' ] );
		// DB::table('account_detail_type')->insert( [ 'account_category_type_id' => 14, 'name' => 'Bad debts',												'description' => 'Use Bad debt to track debt you have written off.' ] );
		// DB::table('account_detail_type')->insert( [ 'account_category_type_id' => 14, 'name' => 'Bank charges', 											'description' => 'Use Bank charges for any fees you pay to financial institutions.' ] );
		// DB::table('account_detail_type')->insert( [ 'account_category_type_id' => 14, 'name' => 'Charitable Contributions', 								'description' => 'Use Charitable contributions to track gifts to charity.' ] );
		// DB::table('account_detail_type')->insert( [ 'account_category_type_id' => 14, 'name' => 'Commissions and fees', 									'description' => 'Use Commissions and fees to track amounts paid to agents (such as brokers) in order for them to execute a trade.' ] );
		// DB::table('account_detail_type')->insert( [ 'account_category_type_id' => 14, 'name' => 'Cost of labour', 											'description' => 'Use Cost of labour to track the cost of paying employees to produce products or supply services. It includes all employment costs, including food and transportation, if applicable. This account is also available as a Cost of Sales (COS) account.' ] );
		// DB::table('account_detail_type')->insert( [ 'account_category_type_id' => 14, 'name' => 'Dues and Subscriptions', 									'description' => 'Use Dues and subscriptions to track dues and subscriptions related to running your business. You may want different accounts of this type for professional dues, fees for licences that cannot be transferred, magazines, newspapers, industry publications, or service subscriptions.' ] );
		// DB::table('account_detail_type')->insert( [ 'account_category_type_id' => 14, 'name' => 'Equipment rental', 										'description' => 'Use Equipment rental to track the cost of renting equipment to produce products or services. This account is also available as a Cost of Sales account. If you purchase equipment, use a Fixed asset account type called Machinery and equipment.' ] );
		// DB::table('account_detail_type')->insert( [ 'account_category_type_id' => 14, 'name' => 'Finance costs', 											'description' => 'Use Finance costs to track the costs of obtaining loans or credit. Examples of finance costs would be credit card fees, interest and mortgage costs.' ] );
		// DB::table('account_detail_type')->insert( [ 'account_category_type_id' => 14, 'name' => 'Income tax expense', 										'description' => 'Use Income tax expense to track income taxes that the company has paid to meet their tax obligations.' ] );
		// DB::table('account_detail_type')->insert( [ 'account_category_type_id' => 14, 'name' => 'Insurance', 												'description' => 'Use Insurance to track insurance payments. You may want different accounts of this type for different types of insurance (auto, general liability, and so on).' ] );
		// DB::table('account_detail_type')->insert( [ 'account_category_type_id' => 14, 'name' => 'Interest paid', 											'description' => 'Use Interest paid for all types of interest you pay, including mortgage interest, finance charges on credit cards, or interest on loans.' ] );
		// DB::table('account_detail_type')->insert( [ 'account_category_type_id' => 14, 'name' => 'Legal and professional fees', 								'description' => 'Use Legal and professional fees to track money to pay to professionals to help you run your business. You may want different accounts of this type for payments to your accountant, attorney, or other consultants.' ] );
		// DB::table('account_detail_type')->insert( [ 'account_category_type_id' => 14, 'name' => 'Loss on discontinued operations, net of tax', 				'description' => 'Use Loss on discontinued operations, net of tax to track the loss realised when a part of the business ceases to operate or when a product line is discontinued.' ] );
		// DB::table('account_detail_type')->insert( [ 'account_category_type_id' => 14, 'name' => 'Management compensation', 									'description' => 'Use Management compensation to track remuneration paid to Management, Executives and non-Executives. For example, salary, fees, and benefits.' ] );
		// DB::table('account_detail_type')->insert( [ 'account_category_type_id' => 14, 'name' => 'Meals and entertainment',	 								'description' => 'Use Meals and entertainment to track how much you spend on dining with your employees to promote morale. If you dine with a customer to promote your business, use a Promotional meals account, instead. Be sure to include who you ate with and the purpose of the meal when you enter the transaction.' ] );
		// DB::table('account_detail_type')->insert( [ 'account_category_type_id' => 14, 'name' => 'Office/General Administrative Expenses', 					'description' => 'Use Office/general administrative expenses to track all types of general or office-related expenses.' ] );
		// DB::table('account_detail_type')->insert( [ 'account_category_type_id' => 14, 'name' => 'Other Miscellaneous Service Cost', 						'description' => 'Use Other miscellaneous service cost to track costs related to providing services that do not fall into another Expense type. This account is also available as a Cost of Sales (COS) account.' ] );
		// DB::table('account_detail_type')->insert( [ 'account_category_type_id' => 14, 'name' => 'Other selling expenses', 									'description' => 'Use Other selling expenses to track selling expenses incurred that do not fall under any other category.' ] );
		// DB::table('account_detail_type')->insert( [ 'account_category_type_id' => 14, 'name' => 'Payroll Expenses', 										'description' => 'Use Payroll expenses to track payroll expenses. You may want different accounts of this type for things like: - Compensation of officers  - Guaranteed payments  - Workers compensation  - Salaries and wages  - Payroll taxes' ] );
		// DB::table('account_detail_type')->insert( [ 'account_category_type_id' => 14, 'name' => 'Rent or Lease of Buildings', 								'description' => 'Use Rent or lease of buildings to track rent payments you make.' ] );
		// DB::table('account_detail_type')->insert( [ 'account_category_type_id' => 14, 'name' => 'Repair and maintenance', 									'description' => 'Use Repair and maintenance to track any repairs and periodic maintenance fees. You may want different accounts of this type to track different types repair & maintenance expenses (auto, equipment, landscape, and so on).' ] );
		// DB::table('account_detail_type')->insert( [ 'account_category_type_id' => 14, 'name' => 'Shipping and delivery expense', 							'description' => 'Use Shipping and delivery expense to track the cost of shipping and delivery of goods to customers.' ] );
		// DB::table('account_detail_type')->insert( [ 'account_category_type_id' => 14, 'name' => 'Supplies and materials', 									'description' => 'Use Supplies & materials to track the cost of raw goods and parts used or consumed when producing a product or providing a service. This account is also available as a Cost of Sales account.' ] );
		// DB::table('account_detail_type')->insert( [ 'account_category_type_id' => 14, 'name' => 'Taxes Paid', 												'description' => 'Use Taxes paid to track taxes you pay. You may want different accounts of this type for payments to different tax agencies.' ] );
		// DB::table('account_detail_type')->insert( [ 'account_category_type_id' => 14, 'name' => 'Travel expenses - general and admin expenses', 			'description' => 'Use Travel expenses - general and admin expenses to track travelling costs incurred that are not directly related to the revenue-generating operation of the company. For example, flight tickets and hotel costs when performing job interviews.' ] );
		// DB::table('account_detail_type')->insert( [ 'account_category_type_id' => 14, 'name' => 'Travel expenses - selling expense', 						'description' => 'Use Travel expenses - selling expense to track travelling costs incurred that are directly related to the revenue-generating operation of the company. For example, flight tickets and hotel costs when selling products and services.' ] );
		// DB::table('account_detail_type')->insert( [ 'account_category_type_id' => 14, 'name' => 'Unapplied Cash Bill Payment Expense', 						'description' => 'Unapplied Cash Bill Payment Expense reports the Cash Basis expense from supplier payment cheques you have sent but not yet applied to supplier bills. In general, you would never use this directly on a purchase or sale transaction.' ] );
		// DB::table('account_detail_type')->insert( [ 'account_category_type_id' => 14, 'name' => 'Utilities', 												'description' => 'Use Utilities to track utility payments. You may want different accounts of this type to track different types of utility payments (gas and electric, telephone, water, and so on).' ] );

		// DB::table('account_detail_type')->insert( [ 'account_category_type_id' => 15, 'name' => 'Amortisation', 												'description' => 'Use Amortisation to track amortisation of intangible assets. Amortisation is spreading the cost of an intangible asset over its useful life, like depreciation of fixed assets. You may want an amortisation account for each intangible asset you have.' ] );
		// DB::table('account_detail_type')->insert( [ 'account_category_type_id' => 15, 'name' => 'Depreciation', 												'description' => 'Use Depreciation to track how much you depreciate fixed assets. You may want a depreciation account for each fixed asset you have.' ] );
		// DB::table('account_detail_type')->insert( [ 'account_category_type_id' => 15, 'name' => 'Exchange Gain or Loss', 									'description' => 'Use Exchange Gain or Loss to track gains or losses that occur as a result of exchange rate fluctuations.' ] );
		// DB::table('account_detail_type')->insert( [ 'account_category_type_id' => 15, 'name' => 'Other Expense', 											'description' => 'Use Other expense to track unusual or infrequent expenses that do not fall into another Other Expense type.' ] );
		// DB::table('account_detail_type')->insert( [ 'account_category_type_id' => 15, 'name' => 'Penalties and settlements', 								'description' => 'Use Penalties and settlements to track money you pay for violating laws or regulations, settling lawsuits, or other penalties.' ] );
    
        DB::table( 'account_detail_type' )->insert( [ 'account_category_type_id' => 1, 'name' => 'Cash' ] );
        DB::table( 'account_detail_type' )->insert( [ 'account_category_type_id' => 1, 'name' => 'Accounts Receivable' ] );
        DB::table( 'account_detail_type' )->insert( [ 'account_category_type_id' => 1, 'name' => 'Merchandise Inventory' ] );
        DB::table( 'account_detail_type' )->insert( [ 'account_category_type_id' => 1, 'name' => 'Supplies' ] );
        DB::table( 'account_detail_type' )->insert( [ 'account_category_type_id' => 1, 'name' => 'Prepaid Insurance' ] );
        DB::table( 'account_detail_type' )->insert( [ 'account_category_type_id' => 1, 'name' => 'Land' ] );
        DB::table( 'account_detail_type' )->insert( [ 'account_category_type_id' => 1, 'name' => 'Buildings' ] );
        DB::table( 'account_detail_type' )->insert( [ 'account_category_type_id' => 1, 'name' => 'Accumulated Depreciation - Buildings' ] );
        DB::table( 'account_detail_type' )->insert( [ 'account_category_type_id' => 1, 'name' => 'Equipment' ] );
        DB::table( 'account_detail_type' )->insert( [ 'account_category_type_id' => 1, 'name' => 'Accumulated Depreciation - Equipment' ] );

        DB::table( 'account_detail_type' )->insert( [ 'account_category_type_id' => 2, 'name' => 'Notes Payable' ] );
        DB::table( 'account_detail_type' )->insert( [ 'account_category_type_id' => 2, 'name' => 'Accounts Payable' ] );
        DB::table( 'account_detail_type' )->insert( [ 'account_category_type_id' => 2, 'name' => 'Wages Payable' ] );
        DB::table( 'account_detail_type' )->insert( [ 'account_category_type_id' => 2, 'name' => 'Interest Payable' ] );
        DB::table( 'account_detail_type' )->insert( [ 'account_category_type_id' => 2, 'name' => 'Unearned Revenues' ] );
        DB::table( 'account_detail_type' )->insert( [ 'account_category_type_id' => 2, 'name' => 'Mortgage Loan Payable' ] );

        DB::table( 'account_detail_type' )->insert( [ 'account_category_type_id' => 3, 'name' => 'Owners Capital' ] );
        DB::table( 'account_detail_type' )->insert( [ 'account_category_type_id' => 3, 'name' => 'Owners Drawing' ] );

        DB::table( 'account_detail_type' )->insert( [ 'account_category_type_id' => 4, 'name' => 'Service Revenues' ] );
        DB::table( 'account_detail_type' )->insert( [ 'account_category_type_id' => 4, 'name' => 'Sales Revenues' ] );

        DB::table( 'account_detail_type' )->insert( [ 'account_category_type_id' => 5, 'name' => 'Salaries Expense' ] );
        DB::table( 'account_detail_type' )->insert( [ 'account_category_type_id' => 5, 'name' => 'Wages Expense' ] );
        DB::table( 'account_detail_type' )->insert( [ 'account_category_type_id' => 5, 'name' => 'Supplies Expense' ] );
        DB::table( 'account_detail_type' )->insert( [ 'account_category_type_id' => 5, 'name' => 'Rent Expense' ] );
        DB::table( 'account_detail_type' )->insert( [ 'account_category_type_id' => 5, 'name' => 'Utilities Expense' ] );
        DB::table( 'account_detail_type' )->insert( [ 'account_category_type_id' => 5, 'name' => 'Postage and Communications' ] );
        DB::table( 'account_detail_type' )->insert( [ 'account_category_type_id' => 5, 'name' => 'Advertising Expense' ] );
        DB::table( 'account_detail_type' )->insert( [ 'account_category_type_id' => 5, 'name' => 'Depreciation Expense' ] );

        DB::table( 'account_detail_type' )->insert( [ 'account_category_type_id' => 6, 'name' => 'Interest Revenues' ] );
        DB::table( 'account_detail_type' )->insert( [ 'account_category_type_id' => 6, 'name' => 'Gain on Sale of Assets' ] );
        DB::table( 'account_detail_type' )->insert( [ 'account_category_type_id' => 6, 'name' => 'Loss on Sale of Assets' ] );
    }
}
